### PR TITLE
Added new option navButtonsAlwaysVisible and fixed hover styles but n…

### PR DESCRIPTION
**Pull request by Diaver**
Hey!
Please take a looks on my PR.
1. I added one new option which is turned off by default 
image
2. Fixed hover style for navigation panels: now they doesn't use 100% vertical space, just 100px and also fixed hover style for that panel - previously it was broken.
The idea for this change is: developer was not able to add buttons on left and right side for carouser item, because they were hovering by navigation panels:
 image

3. Applied small cleanup 

PR checked locally and ready to push.

Actual changes here:
1. 
image
2. 
image

Thanks!

### CODE REVIEW

**Comment by Diaver** [comment]
@Learus Hey! Can you please merge and publish changes?

**Comment by Learus** [comment]
Hello. I am reviewing the changes right now. I have some things I want to point out:

Firstly, I like the option you added (navButtonsAlwaysVisible) and I will push it in the component.

The change on the hover height though, I do not like. By design, the buttonWrapper element is supposed to be 100% height. That is because, if say the buttons are not always visible, the use would have to "guess" where the button is. I want the button to show up, if the user hovers over the general area of the button (aka the buttonWrapper element). Apparently though, that was not working correctly as far as I can tell. This exists only for ease of use purposes.

In any case, the option to add buttons in the sides of the elements could be helpful and wanted, but I think we should find a workaround.

I will look into the changes a bit more.

**Comment by Learus** [comment]
I added both of your changes, and made the full height hover I am talking about above an optional functionality. Thanks for the contribution.

**Comment by Diaver** [comment]
Great, thank you!
Your package is awesome!

**Pull request merged**
