### PR TITLE
feat: make library more compatible with MUI v5

### LINKED ISSUE #130: Remove JSS and @mui/styles
The current version of the carousel mui5 branch still has styles as a peer dep and imports mui styles for `makeStyles`.

I had opened #118 for this a while ago, thought i saw the change somewhere, but i must have been mistaken, as the current release still wants me to have styles installed.

Per the mui5 migration docs, the final step is to remove JSS and `@mui/styles` completely.
https://mui.com/guides/migration-v4/#migrate-from-jss

I'd recommend moving to something like [tss-react](https://github.com/garronej/tss-react) for a fairly easy initial transition, then maybe moving to emotion syntax after.

I can try and make a PR if you can give me the preferred way you'd want this done (tss-react vs emotion/styled components syntax)

### LINKED ISSUE #144: Misalignment when using SSR hydrate() and webpack --mode=production
The Carousel shows the items and the nav buttons etc. in incorrect positions, as you can see in the screenshot.  The issue appears ONLY when the webpack mode is `production` AND when we use `hydrate()` to attach the listeners. Using the`development` mode makes the issue disappear. Using `render()` instead of `hydrate()` also makes it go away.

Source code to reproduce the issue can be found in this GitHub repo: https://github.com/vasansr/mui-carousel-example. 

item-1-issue
item-2-issue
.

### PR DESCRIPTION
**Pull request by matyas-igor**
# Motivation
Remove legacy dependency of `@mui/styles` with minimal code changes and maximal compatibility. Styling of sub-components with classes is still supported. Addresses https://github.com/Learus/react-material-ui-carousel/issues/130 and https://github.com/Learus/react-material-ui-carousel/issues/135.

# List of changes
- removed legacy `@mui/styles` (and thus `jss` dependency)
- converted `makeStyles` into using `styled` helper
- added support for `sx` prop on Carousel container
- added more arguments (`fullHeightHover`, `alwaysVisible`) to NavButton render prop function
- updated documentation

### CODE REVIEW

**Comment by Learus** [comment]
@matyas-igor Thanks! I appreciate the effort! 

I like the idea of moving `navButton` props like `fullHeightHover` and `alwaysInvisible` into the `navButtonProps` prop, but in that case we need to remove them from the original props.

There is no point in having `fullHeightHover` in both the original props and the `navButtonProps`. Also, you forgot the to add the `alwaysInvisible` prop.

Is there a change you could fix those issues?

**Comment by matyas-igor** [comment]
Hey @Learus, thanks a lot for your feedback!

Yes, I agree with your point. Now I'm thinking that it's probably better to remove passing `fullHeightHover` and `alwaysVisible` to NavButton since they're anyway available from the outside, so I'll probably just remove this part now. And anyway it could be added in another PR.

`alwaysInvisible` was not added on purpose, because rendering is called like `{!alwaysInvisible && NavButton({ ... })}` so it's gonna be `false` all the time :)

Another issue is that before `className` passed to NavButton was including many more styles:
```
    const buttonVisibilityClassValue = `${navButtonsAlwaysVisible ? classes.buttonVisible : classes.buttonHidden}`;
    const buttonCssClassValue = `${classes.button} ${buttonVisibilityClassValue} ${fullHeightHover ? classes.fullHeightHoverButton : ""} ${buttonsClass}`;
    ...
    NavButton({ className: buttonCssClassValue })
```
And now it's only `buttonsClass`:
```
    NavButton({ className: buttonsClass })
```
I think it's not super critical, but still may be considered as a breaking change... Should I maybe add passing the same styles as before via `style` prop to NavButton? What do you think?

**Comment by Learus** [comment]
I will have to check out how the new styling system works. When I am familiar with it and able to maintain it, I will merge this PR. Hopefully, that will be within the next few days.

Again, thanks for the effort 😄

**Comment by itsmeurbi** [comment]
Did you forget to remove `npm install @mui/styles` from the `README.md`?

**Pull request merged**
