### PR TITLE
chore: Import withStyles from @material-ui/styles

### PR DESCRIPTION
**Pull request by dplewis**
Closes: https://github.com/Learus/react-material-ui-carousel/issues/94

I recieved the following error on Material UI 5. This PR resolves this issue.

```
TypeError: (0 , _styles.withStyles) is not a function
./node_modules/react-material-ui-carousel/dist/components/Carousel.js
node_modules/react-material-ui-carousel/dist/components/Carousel.js:548
```

`withStyles` was removed from @material-ui/core

See [ChangeLog](https://github.com/mui-org/material-ui/blob/next/CHANGELOG.md#material-uicore500-alpha35)

Let me know if anymore changes are needed.

Thank you for this amazing project!

### CODE REVIEW

**Comment by Bartosz-L** [comment]
Guys, any plans to merge this in near future?

**Comment by Learus** [comment]
Testing MUI 5 a bit with the library, introduces some styling problems, stemming from the change of styling engine used by MUI. It doesn't throw any compiling errors or such, but all the default styles from buttons to indicators do not work correctly. The library's custom styles get overridden by the MUI default styles.

In order to fix this, MUI suggests adding a `StyledEngineProvider` wrapper around the component. This context provider does not exist in MUI 4 sadly. This means, that if we are to upgrade this library to MUI 5 there is no turning back as far as I'm aware.

If there's a way to support both versions please let me know. If not I will leave the library as is until MUI 5 is released officially. Perhaps even, add a branch that implements the migration for anyone that would like it done.

**Comment by aleccaputo** [comment]
@Learus Even if it doesn't look amazing, it does solve this library blocking being able to start an application. As long as the peer deps are still defined as being 4.x, it's at the user's risk to use MUI 5. At least then it's up to the user to try and override/fix the incompatibility of the library or workaround it until it is officially supported.
I'm not a library maintainer though, so that might be bad practice

**Comment by aleccaputo** [comment]
@dplewis Looks like they also changed all the package names in the latest 5.0.0-rc.0

**Comment by dplewis** [comment]
@aleccaputo You are correct, version 5.0.0 was released yesterday. 
@Learus As this is your project could you possibly do an alpha release with this PR. I gave you access to the fork incase you wanted to do some clean up.

**Comment by dplewis** [comment]
If anybody is interested I published a Material UI 5 compatible version on npm.

@Learus sorry but I really need this released. 

https://www.npmjs.com/package/@dplewis/react-material-ui-5-carousel

**Comment by Learus** [comment]
Okay, I will merge this PR into a separate branch called `material-ui-5` and publish a package with a different tag. I will do some clean-up in that branch and rebase the master branch when the time comes.

@dplewis I won't and can't really judge you for implementing this on your own and publishing it, but it would be appreciated if the package you published is deleted (archived?), or points to the original, when the separate release goes live.

Sorry for the late response, I've been very busy. Your initiative made me understand the need for doing better with those kinds of problems.

**Comment by Learus** [comment]
As promised, I've published a release that works with MUI 5 following all the necessary steps found [here](https://mui.com/guides/migration-v4/).

To install the mui5 release simply:
```sh
npm install react-material-ui-carousel@mui5 --save
```

@dplewis Give it a check before I close this PR.

**Comment by aleccaputo** [comment]
@Learus @dplewis 
Thank you!!

**Pull request closed without merging**
